Lists = ['receivers','stocks','barrels','scopes','muzzles','magazines','grips', 'gear', 'tactical']

Receivers = [
    "Airstrike",
    "AK470 Rifle",
    "Ammunition Pod Mk.1",
    "Anti-Materiel Rifle",
    "Assault Rifle",
    "Barricade Mk.1",
    "Bolt-Action Rifle",
    "Bomb",
    "Breech Loaded Pistol",
    "Bullpup Full Auto",
    "Burning Man",
    "Burstfire Pistol",
    "Burstfire Rifle",
    "Burstfire SMG",
    "Cloak",
    "Cloak Mk.2",
    "Combat Knife Mk.1",
    "Combat Knife Mk.2",
    "Combat Rifle",
    "Compound Bow",
    "Crowbar",
    "Digi Grenade Mk.1",
    "EMP Grenade Mk.1",
    "EMP Launcher",
    "Exploding Tomahawk",
    "Flamethrower",
    "Frag Grenade Mk.1",
    "Grenade Launcher",
    "Gunman Hardsuit",
    "Hardsuit Auto-Cannon",
    "Hardsuit Digi Grenade",
    "Hardsuit HRV Decoy",
    "Hardsuit Minigun",
    "Hardsuit Railgun",
    "HE Grenade Mk.1",
    "Heal Injector Mk.1",
    "Heavy Assault Rifle",
    "Heavy Pistol",
    "HRV Blackout Mk.1",
    "HRV Decoy Mk.1",
    "Improvised Shield",
    "Katana",
    "Light Machine Gun",
    "Light Pistol",
    "Light Recon Rifle",
    "LMG Recon",
    "M4X Rifle",
    "Machete",
    "Machine Pistol",
    "Minigun",
    "MK1 Assault AI",
    "None",
    "Overgrown Infected Finger Nails",
    "Personal Holo-decoy",
    "Prestige Assault Rifle",
    "Prestige Light Pistol",
    "Proximity Mine Mk.1",
    "Railgun",
    "Repair Tool",
    "Respawn Beacon",
    "Revival Injector Mk.1",
    "Revolver",
    "Rhino Hardsuit",
    "Riot Shield",
    "Rocket Stinger",
    "Rocket Swarm",
    "Shock Grenade Mk.1",
    "Shotgun",
    "Shotgun AR-k",
    "Snub 260",
    "Sonic Tomahawk",
    "Stun Mine Mk.1",
    "Stun Shuriken",
    "Submachine Gun",
    "Tactical Assault Rifle",
    "Tactical Ice Axe",
    "Tactical SMG",
    "Throwing Knives Mk.1",
    "Toxic Breach Hammer",
    "Toxic Grenade Mk.1",
    "Turret"
]

Stocks = [
    "Silverwood z1200 BPFA",
    "Hullbreach 89-BPFA",
    "Briar Elite A4-BS",
    "Redsand Compensator Stock",
    "No Stock",
    "Prestige Silverwood Standard Stock",
    "MMRS BP-CQ + PCR",
    "MMRS BP-XLi",
    "MMRS BP-SR Tactical",
    "ArmCom Folding Stock",
    "Overmatch Compensator Stock",
    "Silverwood Standard Stock",
    "Hullbreach CQC Stock",
    "Krane Tactical Stock",
    "Taurex Stabilizing Stock",
    "Silverwood Compensator Stock",
    "V2 Folding Stock",
    "Vulcan Extender Stock",
    "Krane Extender Stock",
    "ArmCom Compensator Stock",
    "Krane Ultralight Stock",
    "Frontier Ultralight Stock"
]

Barrels = [
    "ArmCom Assault Barrel",
    "Armcom BAR-01",
    "Armcom BARl1",
    "Briar Accuracy Barrel",
    "Briar Assault Barrel",
    "Briar Balanced Barrel",
    "Briar BAR Grip",
    "Briar BAR-02",
    "Briar CQC Barrel",
    "Briar Lightweight Barrel",
    "Frontier Compensator Barrel",
    "Frontier Standard Barrel",
    "Hullbreach 047BAR",
    "Hullbreach 057BAR",
    "Krane Assault Barrel",
    "Krane Heavy Assault Barrel",
    "Krane SG Bar-20",
    "Leatherneck Accuracy Barrel",
    "No Barrel Mod",
    "No Grip",
    "Ogre CQC Barrel",
    "Overmatch M-CV Breach",
    "Prestige Frontier Standard Barrel",
    "Raider Snub Barrel",
    "Redsand CQC Barrel",
    "Silverwood CQC Barrel",
    "Silverwood Light Accuracy Barrel",
    "Silverwood SW-09",
    "Silverwood TechBAR",
    "Titan Assault Barrel",
    "Titan Extended Barrel",
    "Titan FFB",
    "V2 X200 Mod",
    "V2 Z900 Mod",
    "Vulcan Lightweight Barrel",
    "Vulcan Tactical Barrel",
    "Overmatch A-12 Blast",
    "Overmatch Heavy X3",
    "Overmatch CRC-7 Post"
]

Scopes = [
    "4X Ammo Counter Scope",
    "Aim Point Ammo Counter",
    "ArmCom CQC Scope",
    "ArmCom Infrared Scope",
    "ArmCom Sniper Scope",
    "EMI ACOG Scope",
    "EMI Electric Scope",
    "EMI Infrared Scope",
    "EMI Infrared Scope Mk. 2",
    "EMI Tech Scope",
    "EON Electric Scope",
    "Frontier Sniper Scope",
    "invalid scope",
    "Krane Holo Sight",
    "Krane Sniper Scope",
    "Krane Tactical Scope",
    "Lightsky Red Dot Sight",
    "Lightsky Reflex Sight",
    "MMRS Flip-Up Rail Sight",
    "No Optic Mod",
    "OPRL Holo Sight",
    "Prestige Titan Rail Sight",
    "Silverwood Combo Scope",
    "Silverwood Heavy Scope",
    "Titan Rail Sight"
]

Muzzles = [
    "0 = None",
    "1 = ArmCom Slit Flash breaker",
    "2 = Nexus Extended Range Muzzle",
    "3 = Frontier Standard Suppressor",
    "4 = Briar Dampening Muzzle",
    "5 = Vulcan Notched Flash breaker",
    "6 = Briar Enhanced Suppressor",
    "7 = Vulcan Compensator",
    "8 = Vulcan Longreach Flash breaker",
    "9 = Overmatch Muzzle Shroud",
    "10 = ArmCom Enhanced Suppressor",
    "11 = Frontier Power Muzzle",
    "12 = Silverwood Flash breaker",
    "13 = Vulcan Power Brake",
    "14 = Krane Power Muzzle",
    "15 = Briar Extender Muzzle",
    "16 = ArmCom Power Muzzle",
    "17 = ArmCom Balanced Muzzle",
    "18 = Gold"
]

Magazines = [
    "0 = SMG Standard",
    "1 = SMG Light",
    "2 = SMG Quick",
    "3 = SMG Extended",
    "4 = SMG Express",
    "5 = SMG Electro",
    "6 = SMG Explosive",
    "7 = SMG Incendiary",
    "8 = SMG Toxic",
    "9 = AssaultRifle Standard",
    "10 = AssaultRifle Light",
    "11 = AssaultRifle Quick",
    "12 = AssaultRifle Extended",
    "13 = AssaultRifle Express",
    "14 = AssaultRifle Drummed",
    "15 = AssaultRifle Relentless",
    "16 = AssaultRifle Electro",
    "17 = AssaultRifle Explosive",
    "18 = AssaultRifle Incendiary",
    "19 = AssaultRifle Toxic",
    "20 = Combat Rifle Standard",
    "21 = Combat Rifle Light",
    "22 = Combat Rifle Quick",
    "23 = Combat Rifle Extended",
    "24 = Combat Rifle Express",
    "25 = Combat Rifle Electro",
    "26 = Combat Rifle Explosive",
    "27 = Combat Rifle Incendiary",
    "28 = Combat Rifle Toxic",
    "29 = Shotgun Standard",
    "30 = Shotgun Light",
    "31 = Shotgun Quick",
    "32 = Shotgun Extended",
    "33 = Shotgun Express",
    "34 = Shotgun Drummed",
    "35 = Shotgun Electro",
    "36 = Shotgun Explosive",
    "37 = Shotgun Incendiary",
    "38 = Shotgun Toxic",
    "39 = LMG Standard",
    "40 = LMG Quick",
    "41 = LMG Electro",
    "42 = LMG Explosive",
    "43 = LMG Incendiary",
    "44 = LMG Toxic",
    "45 = Heavy Pistol Standard",
    "46 = Heavy Pistol Light",
    "47 = Heavy Pistol Quick",
    "48 = Heavy Pistol Extended",
    "49 = Heavy Pistol Express",
    "50 = Heavy Pistol Electro",
    "51 = Heavy Pistol Explosive",
    "52 = Heavy Pistol Incendiary",
    "53 = Heavy Pistol Toxic",
    "54 = Light Pistol Standard",
    "55 = Light Pistol Light",
    "56 = Light Pistol Quick",
    "57 = Light Pistol Extended",
    "58 = Light Pistol Express",
    "59 = Light Pistol Electro",
    "60 = Light Pistol Explosive",
    "61 = Light Pistol Incendiary",
    "62 = Light Pistol Toxic",
    "63 = Machine Pistol Standard",
    "64 = Machine Pistol Light",
    "65 = Machine Pistol Quick",
    "66 = Machine Pistol Extended",
    "67 = Machine Pistol Express",
    "68 = Machine Pistol Electro",
    "69 = Machine Pistol Explosive",
    "70 = Machine Pistol Incendiary",
    "71 = Machine Pistol Toxic",
    "72 = Burstfire Pistol Standard",
    "73 = Burstfire Pistol Light",
    "74 = Burstfire Pistol Quick",
    "75 = Burstfire Pistol Extended",
    "76 = Burstfire Pistol Express",
    "77 = Burstfire Pistol Electro",
    "78 = Burstfire Pistol Explosive",
    "79 = Burstfire Pistol Incendiary",
    "80 = Burstfire Pistol Toxic",
    "81 = Burstfire Rifle Standard",
    "82 = Burstfire Rifle Light",
    "83 = Burstfire Rifle Quick",
    "84 = Burstfire Rifle Extended",
    "85 = Burstfire Rifle Express",
    "86 = Burstfire Rifle Electro",
    "87 = Burstfire Rifle Explosive",
    "88 = Burstfire Rifle Incendiary",
    "89 = Burstfire Rifle Toxic",
    "90 = Bolt-Action Rifle Standard",
    "91 = Bolt-Action Rifle Light",
    "92 = Bolt-Action Rifle Quick",
    "93 = Bolt-Action Rifle Extended",
    "94 = Bolt-Action Rifle Express",
    "95 = Bolt-Action Rifle Electro",
    "96 = Bolt-Action Rifle Explosive",
    "97 = Bolt-Action Rifle Incendiary",
    "98 = Bolt-Action Rifle Toxic",
    "99 = Revolver Standard",
    "100 = Revolver Electro",
    "101 = Revolver Explosive",
    "102 = Revolver Incendiary",
    "103 = Revolver Toxic",
    "104 = LMG Recon Standard",
    "105 = LMG Recon Light",
    "106 = LMG Recon Heavy",
    "107 = Tactical SMG Standard",
    "108 = Tactical SMG Light",
    "109 = Tactical SMG Quick",
    "110 = Tactical SMG Extended",
    "111 = Tactical SMG Electro",
    "112 = Tactical SMG Explosive",
    "113 = Tactical SMG Incendiary",
    "114 = Tactical SMG Toxic",
    "115 = Heavy Assault Rifle Standard",
    "116 = Heavy Assault Rifle Light",
    "117 = Heavy Assault Rifle Quick",
    "118 = Heavy Assault Rifle Extended",
    "119 = Heavy Assault Rifle Express",
    "120 = Heavy Assault Rifle Electro",
    "121 = Heavy Assault Rifle Explosive",
    "122 = Heavy Assault Rifle Incendiary",
    "123 = Heavy Assault Rifle Toxic",
    "124 = Shotgun AR-k Standard",
    "125 = Shotgun AR-k Light",
    "126 = Shotgun AR-k Quick",
    "127 = Shotgun AR-k Extended",
    "128 = Shotgun AR-k Express",
    "129 = Shotgun AR-k Electro",
    "130 = Shotgun AR-k Explosive",
    "131 = Shotgun AR-k Incendiary",
    "132 = Shotgun AR-k Toxic",
    "133 = Shotgun AR-k Drummed",
    "134 = Breech Loaded Pistol Explosive",
    "135 = Breech Loaded Pistol Incendiary",
    "136 = LMG Recon Electro",
    "137 = LMG Recon Explosive",
    "138 = LMG Recon Incendiary",
    "139 = LMG Recon Toxic",
    "140 = Burstfire SMG Standard",
    "141 = Burstfire SMG Light",
    "142 = Burstfire SMG Quick",
    "143 = Burstfire SMG Extended",
    "144 = Burstfire SMG Express",
    "145 = Burstfire SMG Electro",
    "146 = Burstfire SMG Explosive",
    "147 = Burstfire SMG Incendiary",
    "148 = Burstfire SMG Toxic",
    "149 = Bullpup Full Auto Standard",
    "150 = Bullpup Full Auto Light",
    "151 = Bullpup Full Auto Quick",
    "152 = Bullpup Full Auto Extended",
    "153 = Bullpup Full Auto Express",
    "154 = Bullpup Full Auto Electro",
    "155 = Bullpup Full Auto Explosive",
    "156 = Bullpup Full Auto Incendiary",
    "157 = Bullpup Full Auto Toxic",
    "158 = SMG Magnum",
    "159 = Burstfire SMG Magnum",
    "160 = AssaultRifle Magnum",
    "161 = Burstfire Rifle Magnum",
    "162 = Heavy Assault Rifle Magnum",
    "163 = Bullpup Full Auto Magnum",
    "164 = Combat Rifle Magnum",
    "165 = Bolt-Action Rifle Magnum",
    "166 = Shotgun Magnum",
    "167 = Shotgun AR-k Magnum",
    "168 = LMG Magnum",
    "169 = Heavy Pistol Magnum",
    "170 = Light Pistol Magnum",
    "171 = Machine Pistol Magnum",
    "172 = Burstfire Pistol Magnum",
    "173 = Revolver Magnum",
    "174 = Tactical SMG Magnum",
    "175 = LMG Recon Magnum",
    "176 = Breech Loaded Pistol Scattershot",
    "177 = Snub 260 Standard",
    "178 = Snub 260 Precision",
    "179 = Snub 260 High Caliber",
    "180 = Snub 260 Incendiary",
    "181 = Snub 260 Electro",
    "182 = Snub 260 Explosive",
    "183 = Snub 260 Toxic",
    "184 = Snub 260 Magnum",
    "185 = M4X Rifle Standard",
    "186 = M4X Rifle Light",
    "187 = M4X Rifle Quick",
    "188 = M4X Rifle Extended",
    "189 = M4X Rifle Express",
    "190 = M4X Rifle Electro",
    "191 = M4X Rifle Explosive",
    "192 = M4X Rifle Incendiary",
    "193 = M4X Rifle Toxic",
    "194 = M4X Rifle Magnum",
    "195 = AK470 Rifle Standard",
    "196 = AK470 Rifle Light",
    "197 = AK470 Rifle Quick",
    "198 = AK470 Rifle Extended",
    "199 = AK470 Rifle Express",
    "200 = AK470 Rifle Electro",
    "201 = AK470 Rifle Explosive",
    "202 = AK470 Rifle Incendiary",
    "203 = AK470 Rifle Toxic",
    "204 = AK470 Rifle Magnum",
    "205 = Compound Bow Standard",
    "206 = Compound Bow Explosive",
    "207 = Compound Bow Stun",
    "208 = Compound Bow Poison",
    "209 = Compound Bow Light",
    "210 = Compound Bow Heavy",
    "211 = Compound Bow Cupid",
    "212 = Tactical Assault Rifle Standard",
    "213 = Tactical Assault Rifle Light",
    "214 = Tactical Assault Rifle Quick",
    "215 = Tactical Assault Rifle Extended",
    "216 = Tactical Assault Rifle Express",
    "217 = Tactical Assault Rifle Electro",
    "218 = Tactical Assault Rifle Explosive",
    "219 = Tactical Assault Rifle Incendiary",
    "220 = Tactical Assault Rifle Toxic",
    "221 = Light Recon Rifle Standard",
    "222 = Light Recon Rifle Light",
    "223 = Light Recon Rifle Quick",
    "224 = Light Recon Rifle Extended",
    "225 = Light Recon Rifle Express",
    "226 = Rifle Prestige Standard",
    "227 = Pistol Prestige Standard"
]

Tags = []

Grips = [
    "Briar BrGR1",
    "Briar BrSGP1"
]

AmmoTypes = [
    "Magnum Ammo",
    "Toxic Rounds",
    "Incendiary Rounds",
    "Hollow Point Rounds",
    "Explosive Rounds",
    "Electro Rounds",
    "Standard Rounds",
    "Armor Piercing Rounds"
]

Gear = [
    "0 = No Gear",
    "1 = Frag Grenade Mk.1",
    "2 = Combat Knife Mk.1",
    "3 = Shock Grenade Mk.1",
    "4 = EMP Grenade Mk.1",
    "5 = Digi Grenade Mk.1",
    "6 = Proximity Mine Mk.1",
    "7 = HRV Decoy Mk.1",
    "8 = Stun Mine Mk.1",
    "9 = Toxic Grenade Mk.1",
    "10 = HE Grenade Mk.1",
    "11 = HRV Blackout Mk.1",
    "12 = Combat Knife Mk.2",
    "13 = Machete",
    "14 = Breach Hammer",
    "15 = Throwing Knives Mk.1",
    "16 = Black Mesa Crowbar",
    "17 = Golden Crowbar",
    "18 = Silver Crowbar",
    "19 = Exploding Tomahawk",
    "20 = Incendiary Protection Gear",
    "21 = Toxic Protection Gear",
    "22 = Explosive Protection Gear",
    "23 = Electro Protection Gear",
    "24 = Melee Protection Gear",
    "25 = Personal Holo-decoy",
    "26 = Stun Shuriken",
    "27 = Sonic Tomahawk",
    "28 = Infrared Protection Gear",
    "29 = Overgrown Infected Finger Nails",
    "30 = Burning Man",
    "31 = Overgrown Hulk Finger Nails",
    "32 = Overgrown Infected Dog Finger Nails",
    "33 = Toxic Breach Hammer",
    "34 = Frag Mk.1 - Lightning Trail Mod",
    "35 = Frag Mk.1 - Lightning Trail and Strike Mod",
    "36 = Frag Mk.1 - Flame Mod",
    "37 = Frag Mk.1 - Fire Mod",
    "38 = Frag Mk.1 - Lightning Strike Mod",
    "39 = Frag Mk.1 - Blue Explosion Mod",
    "40 = Frag Mk.1 - Pink Explosion Mod",
    "41 = Frag Mk.1 - Purple Explosion Mod",
    "42 = Frag Mk.1 - Red Explosion Mod",
    "43 = Frag Mk.1 - Blue and Yellow Explosion Mod",
    "44 = Frag Mk.1 - Blue BOOM Explosion Mod",
    "45 = Frag Mk.1 - Butterfly Mod",
    "46 = Snowpocalypse",
    "47 = Tactical Ice Axe",
    "48 = Nor'Easter",
    "49 = Prestige Frag Grenade Mk.1",
    "50 = Prestige Combat Knife Mk.1",
    "51 = I Heart U"
]

Tactical = [
    "0 = No Tactical Gear",
    "1 = Heal Injector Mk.1",
    "2 = Repair Tool",
    "3 = Ammunition Pod Mk.1",
    "4 = Barricade Mk.1",
    "5 = Revival Injector Mk.1",
    "6 = Cloak",
    "7 = Hardsuit HRV Ping",
    "8 = Hardsuit Battle Mode",
    "9 = Respawn Beacon",
    "10 = Firewall Breach Kit",
    "11 = HRV Cloak",
    "12 = Cloak Mk.2",
    "13 = Barricade Mk.2",
    "14 = Improvised Shield"
]