Lists = ['receivers']

Receivers = [
    "Gunman Hardsuit",
    "Rhino Hardsuit",
    "Rocket Swarm",
    "Railgun",
    "Minigun",
    "Personal Holo-decoy",
    "MK1 Assault AI",
    "Stun Shuriken",
    "Snub 260",
    "Hardsuit HRV Decoy",
    "Hardsuit Digi Grenade",
    "Hardsuit Minigun",
    "Hardsuit Railgun",
    "Hardsuit Auto-Cannon",
    "Crowbar",
    "Crowbar",
    "EMP Launcher",
    "Throwing Knives Mk.1",
    "Crowbar",
    "Burstfire SMG",
    "Tactical SMG",
    "LMG Recon",
    "Breech Loaded Pistol",
    "Shotgun AR-k",
    "Heavy Assault Rifle",
    "Digi Grenade Mk.1",
    "Bullpup Full Auto",
    "Respawn Beacon",
    "Anti-Materiel Rifle",
    "Sonic Tomahawk",
    "Katana",
    "Exploding Tomahawk",
    "Toxic Grenade Mk.1",
    "Toxic Breach Hammer",
    "Compound Bow",
    "M4X Rifle",
    "AK470 Rifle",
    "Light Machine Gun",
    "Assault Rifle",
    "Tactical Assault Rifle",
    "Bolt-Action Rifle",
    "Bomb",
    "Overgrown Infected Finger Nails",
    "Burning Man",
    "Overgrown Infected Finger Nails",
    "Improvised Shield",
    "Shotgun",
    "Prestige Assault Rifle",
    "Burstfire Rifle",
    "Light Recon Rifle",
    "Combat Rifle",
    "Submachine Gun",
    "Revival Injector Mk.1",
    "HRV Blackout Mk.1",
    "HRV Decoy Mk.1",
    "Frag Grenade Mk.1",
    "Combat Knife Mk.1",
    "Cloak Mk.2",
    "Cloak",
    "Ammunition Pod Mk.1",
    "Stun Mine Mk.1",
    "Combat Knife Mk.2",
    "Repair Tool",
    "Proximity Mine Mk.1",
    "Machete",
    "Tactical Ice Axe",
    "Heal Injector Mk.1",
    "HE Grenade Mk.1",
    "Frag Grenade Mk.1",
    "EMP Grenade Mk.1",
    "Shock Grenade Mk.1",
    "Combat Knife Mk.1",
    "Riot Shield",
    "Barricade Mk.1",
    "Prestige Light Pistol",
    "Machine Pistol",
    "Shotgun",
    "Revolver",
    "Light Pistol",
    "Heavy Pistol",
    "Burstfire Pistol",
    "Flamethrower",
    "Grenade Launcher",
    "Rocket Stinger",
    "Turret",
    "Airstrike"
]