Lists = ['receivers','stocks','barrels','scopes']

Receivers = [
    "Airstrike",
    "AK470 Rifle",
    "Ammunition Pod Mk.1",
    "Anti-Materiel Rifle",
    "Assault Rifle",
    "Barricade Mk.1",
    "Bolt-Action Rifle",
    "Bomb",
    "Breech Loaded Pistol",
    "Bullpup Full Auto",
    "Burning Man",
    "Burstfire Pistol",
    "Burstfire Rifle",
    "Burstfire SMG",
    "Cloak Mk.2",
    "Cloak",
    "Combat Knife Mk.1",
    #"Combat Knife Mk.1",
    "Combat Knife Mk.2",
    "Combat Rifle",
    "Compound Bow",
    "Crowbar",
    #"Crowbar",
    #"Crowbar",
    "Digi Grenade Mk.1",
    "EMP Grenade Mk.1",
    "EMP Launcher",
    "Exploding Tomahawk",
    "Flamethrower",
    "Frag Grenade Mk.1",
    "Frag Grenade Mk.1",
    "Grenade Launcher",
    "Gunman Hardsuit",
    "Hardsuit Auto-Cannon",
    "Hardsuit Digi Grenade",
    "Hardsuit HRV Decoy",
    "Hardsuit Minigun",
    "Hardsuit Railgun",
    "HE Grenade Mk.1",
    "Heal Injector Mk.1",
    "Heavy Assault Rifle",
    "Heavy Pistol",
    "HRV Blackout Mk.1",
    "HRV Decoy Mk.1",
    "Improvised Shield",
    "Katana",
    "Light Machine Gun",
    "Light Pistol",
    "Light Recon Rifle",
    "LMG Recon",
    "M4X Rifle",
    "Machete",
    "Machine Pistol",
    "Minigun",
    "MK1 Assault AI",
    "Overgrown Infected Finger Nails",
    #"Overgrown Infected Finger Nails",
    "Personal Holo-decoy",
    "Prestige Assault Rifle",
    "Prestige Light Pistol",
    "Proximity Mine Mk.1",
    "Railgun",
    "Repair Tool",
    "Respawn Beacon",
    "Revival Injector Mk.1",
    "Revolver",
    "Rhino Hardsuit",
    "Riot Shield",
    "Rocket Stinger",
    "Rocket Swarm",
    "Shock Grenade Mk.1",
    "Shotgun AR-k",
    "Shotgun",
    #"Shotgun",
    "Snub 260",
    "Sonic Tomahawk",
    "Stun Mine Mk.1",
    "Stun Shuriken",
    "Submachine Gun",
    "Tactical Assault Rifle",
    "Tactical Ice Axe",
    "Tactical SMG",
    "Throwing Knives Mk.1",
    "Toxic Breach Hammer",
    "Toxic Grenade Mk.1",
    "Turret"
]

Stocks = [
    "ArmCom Compensator Stock",
    "ArmCom Folding Stock",
    "Frontier Ultralight Stock",
    "Hullbreach CQC Stock",
    "Krane Extender Stock",
    "Krane Tactical Stock",
    "Krane Ultralight Stock",
    "Overmatch Compensator Stock",
    "Redsand Compensator Stock",
    "Silverwood Compensator Stock",
    "Silverwood Standard Stock",
    "Taurex Stabilizing Stock",
    "V2 Folding Stock",
    "Vulcan Extender Stock"
]

Barrels = [
    "ArmCom Assault Barrel",
    "Briar Accuracy Barrel",
    "Briar Assault Barrel",
    "Briar Balanced Barrel",
    "Briar CQC Barrel",
    "Briar Lightweight Barrel",
    "Frontier Compensator Barrel",
    "Frontier Standard Barrel",
    "Krane Assault Barrel",
    "Krane Heavy Assault Barrel",
    "Krane SG Bar-20",
    "Leatherneck Accuracy Barrel",
    "Ogre CQC Barrel",
    "Overmatch M-CV Breach",
    "Raider Snub Barrel",
    "Redsand CQC Barrel",
    "Silverwood CQC Barrel",
    "Silverwood Light Accuracy Barrel",
    "Silverwood SW-09",
    "Titan Assault Barrel",
    "Titan Extended Barrel",
    "Titan FFB",
    "V2 X200 Mod",
    "V2 Z900 Mod",
    "Vulcan Lightweight Barrel",
    "Vulcan Tactical Barrel"
]

Scopes = [
    "ArmCom CQC Scope",
    "ArmCom Sniper Scope",
    "EMI ACOG Scope",
    "EMI Electric Scope",
    "EMI Tech Scope",
    "EON Electric Scope",
    "Frontier Sniper Scope",
    "invalid scope",
    "Krane Holo Sight",
    "Krane Sniper Scope",
    "Krane Tactical Scope",
    "Lightsky Red Dot Sight",
    "Lightsky Reflex Sight",
    "MMRS Flip-Up Rail Sight",
    "OPRL Holo Sight",
    "Silverwood Combo Scope",
    "Silverwood Heavy Scope",
    "Titan Rail Sight"
]